version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx-ssl
        ports:
            - "443:443"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./.docker/certs:/etc/nginx/ssl:ro
        depends_on:
            - laravel.test
        networks:
            - sail

networks:
    sail:
        driver: bridge
