version: '3'
services:
    laravel:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www'
        working_dir: /var/www
        command: bash -c "php artisan serve --host=0.0.0.0 --port=80"
        networks:
            - sail
        depends_on:
            - mysql

    nginx:
        image: 'nginx:alpine'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '.:/var/www'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/ssl:/etc/nginx/ssl'
        networks:
            - sail
        depends_on:
            - laravel

    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'wo_tracker'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD-SHELL
                - mysqladmin ping -p$${MYSQL_PASSWORD}
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8081}:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 128M
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
